// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main.proto

package com.tencent.mars.proto;

public final class Main {
  private Main() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.tencent.mars.proto.CmdID}
   */
  public enum CmdID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CMD_ID_INVALID = -1;</code>
     */
    CMD_ID_INVALID(0, -1),
    /**
     * <code>CMD_ID_UNKNOWN = 0;</code>
     */
    CMD_ID_UNKNOWN(1, 0),
    /**
     * <code>CMD_ID_HELLO = 1;</code>
     */
    CMD_ID_HELLO(2, 1),
    /**
     * <code>CMD_ID_AUTH = 2;</code>
     */
    CMD_ID_AUTH(3, 2),
    /**
     * <code>CMD_ID_SEND_MESSAGE = 3;</code>
     */
    CMD_ID_SEND_MESSAGE(4, 3),
    /**
     * <code>CMD_ID_CONVERSATION_LIST = 4;</code>
     */
    CMD_ID_CONVERSATION_LIST(5, 4),
    /**
     * <code>CMD_ID_JOINTOPIC = 5;</code>
     */
    CMD_ID_JOINTOPIC(6, 5),
    /**
     * <code>CMD_ID_NOOPING = 6;</code>
     */
    CMD_ID_NOOPING(7, 6),
    /**
     * <code>CMD_ID_LEFTTOPIC = 7;</code>
     */
    CMD_ID_LEFTTOPIC(8, 7),
    /**
     * <code>CMD_ID_HELLO2 = 8;</code>
     */
    CMD_ID_HELLO2(9, 8),
    ;

    /**
     * <code>CMD_ID_INVALID = -1;</code>
     */
    public static final int CMD_ID_INVALID_VALUE = -1;
    /**
     * <code>CMD_ID_UNKNOWN = 0;</code>
     */
    public static final int CMD_ID_UNKNOWN_VALUE = 0;
    /**
     * <code>CMD_ID_HELLO = 1;</code>
     */
    public static final int CMD_ID_HELLO_VALUE = 1;
    /**
     * <code>CMD_ID_AUTH = 2;</code>
     */
    public static final int CMD_ID_AUTH_VALUE = 2;
    /**
     * <code>CMD_ID_SEND_MESSAGE = 3;</code>
     */
    public static final int CMD_ID_SEND_MESSAGE_VALUE = 3;
    /**
     * <code>CMD_ID_CONVERSATION_LIST = 4;</code>
     */
    public static final int CMD_ID_CONVERSATION_LIST_VALUE = 4;
    /**
     * <code>CMD_ID_JOINTOPIC = 5;</code>
     */
    public static final int CMD_ID_JOINTOPIC_VALUE = 5;
    /**
     * <code>CMD_ID_NOOPING = 6;</code>
     */
    public static final int CMD_ID_NOOPING_VALUE = 6;
    /**
     * <code>CMD_ID_LEFTTOPIC = 7;</code>
     */
    public static final int CMD_ID_LEFTTOPIC_VALUE = 7;
    /**
     * <code>CMD_ID_HELLO2 = 8;</code>
     */
    public static final int CMD_ID_HELLO2_VALUE = 8;


    public final int getNumber() { return value; }

    public static CmdID valueOf(int value) {
      switch (value) {
        case -1: return CMD_ID_INVALID;
        case 0: return CMD_ID_UNKNOWN;
        case 1: return CMD_ID_HELLO;
        case 2: return CMD_ID_AUTH;
        case 3: return CMD_ID_SEND_MESSAGE;
        case 4: return CMD_ID_CONVERSATION_LIST;
        case 5: return CMD_ID_JOINTOPIC;
        case 6: return CMD_ID_NOOPING;
        case 7: return CMD_ID_LEFTTOPIC;
        case 8: return CMD_ID_HELLO2;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CmdID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdID>() {
            public CmdID findValueByNumber(int number) {
              return CmdID.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Main.getDescriptor().getEnumTypes().get(0);
    }

    private static final CmdID[] VALUES = values();

    public static CmdID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CmdID(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.tencent.mars.proto.CmdID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nmain.proto\022\026com.tencent.mars.proto*\345\001\n" +
      "\005CmdID\022\033\n\016CMD_ID_INVALID\020\377\377\377\377\377\377\377\377\377\001\022\022\n\016C" +
      "MD_ID_UNKNOWN\020\000\022\020\n\014CMD_ID_HELLO\020\001\022\017\n\013CMD" +
      "_ID_AUTH\020\002\022\027\n\023CMD_ID_SEND_MESSAGE\020\003\022\034\n\030C" +
      "MD_ID_CONVERSATION_LIST\020\004\022\024\n\020CMD_ID_JOIN" +
      "TOPIC\020\005\022\022\n\016CMD_ID_NOOPING\020\006\022\024\n\020CMD_ID_LE" +
      "FTTOPIC\020\007\022\021\n\rCMD_ID_HELLO2\020\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
